name: Run Unit Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    env:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        secrets: '*secret*'
        parse_json: true